remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Un repository per creare in un attimo un semplice sito web
description: Un repository per creare in un attimo un semplice sito web
lang: it-IT
