remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
title: Un repository per creare in un attimo un semplice sito web
description: Un repository per creare in un attimo un semplice sito web
lang: it-IT
